server:
  port: 8081
spring:
  application:
    name: xhdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xhdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 119.96.220.82
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.xhdp.entity # 别名扫描包
logging:
  level:
    com.xhdp: debug
  pattern:
    dateformat: mm:ss.SSS